/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;
import controller.ProjectController;
import java.sql.Connection;
import java.util.List;
import model.Project;
import util.ConnectionFactory;

public class App {

    public static void main(String[] args) {
        
//        ProjectController projController = new ProjectController();
        
//        Project proj = new Project();
        
//        projController.save(proj);
//        proj.setId(1);
//        proj.setName("New project name");
//        proj.setDescription("description");
//        projController.update(proj);
//        
//        List<Project> projects = projController.getAll();
//        System.out.println("Total projects: "+projects.size());
        
//        projController.removeById(0);
    }
}
